### PR TITLE
Cool beans README!

### PR DESCRIPTION
**Pull request by Wyatt-Stanke**

### CODE REVIEW

**Review by davidstanke — CHANGES_REQUESTED** [review]
Ha ha cute. These are good changes, but please:
- remove the rickroll
- for formatting, use markdown unless html is absolutely necessary (I don't think it is in this case)

**Comment by Wyatt-Stanke** [comment]
> Ha ha cute. These are good changes, but please:
> 
> * remove the rickroll
> * for formatting, use markdown unless html is absolutely necessary (I don't think it is in this case)

I was going to remove the rickroll, it's just temporary.
2. Ok!

**Comment by Wyatt-Stanke** [comment]
To have the text centered, you have to use html.

**Review by davidstanke — APPROVED** [review]

**Comment by Wyatt-Stanke** [comment]
I'm going to try again.

**Pull request closed without merging**
